# -*- coding: utf-8 -*-
"""04mar_assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YMpt7RN9f4l7BEaoqTYlCPwvbVKX0JfS
"""

#1.
import seaborn as sns
import plotly.express as px

# Load the "titanic" dataset
titanic_df = sns.load_dataset("titanic")

# Create a scatter plot using Plotly Express
fig = px.scatter(titanic_df, x="age", y="fare")

# Show the plot
fig.show()

#2.
import plotly.express as px
import plotly.graph_objs as go
from plotly.subplots import make_subplots

# Load the "tips" dataset
tips_df = px.data.tips()

# Create a box plot using Plotly Express
fig = px.box(tips_df, x="day", y="total_bill", color="smoker")

# Show the plot
fig.show()

#3.
import plotly.express as px

# Load the "tips" dataset
tips_df = px.data.tips()

# Create a histogram with markers colored by "day" and shaped by "smoker"
fig = px.histogram(tips_df, x="sex", y="total_bill", color="day", marginal="box", 
                   barmode="group", nbins=10, pattern_shape="smoker")

# Show the plot
fig.show()

#4.
import plotly.express as px

# Load the "iris" dataset
iris_df = px.data.iris()

# Create a scatter matrix plot with markers colored by "species"
fig = px.scatter_matrix(iris_df, dimensions=["sepal_length", "sepal_width", "petal_length", "petal_width"], 
                        color="species")

# Show the plot
fig.show()

#5.
'''distplot is a plot type that shows the distribution of a dataset, usually represented as a histogram or a kernel density estimate (KDE). It is a useful tool for understanding the shape and spread of data.

Here's an example of how to create a distplot using Plotly Express:'''
import plotly.express as px

# Load the "tips" dataset
tips_df = px.data.tips()

# Create a distplot of the "total_bill" column
fig = px.histogram(tips_df, x="total_bill", marginal="rug", nbins=30)

# Show the plot
fig.show()

